# This is a basic workflow to help you get started with Actions

name: heif2jpg

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependences & build images
        run: |
          print_header() {
             lightcyan='\033[1;36m'
             nocolor='\033[0m'
             echo -e "${lightcyan}$1${nocolor}"
          }
          print_header "Install dependeces"
          sudo apt install libheif-examples
          print_header "Run script"
          cd ..
          tree
          
          
