# This is a basic workflow to help you get started with Actions

name: heif2jpg

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependences & build images
        run: |
          chmod +x ./script.sh
          ./script.sh
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: $(date +'%Y-%m-%d-%T')


