# This is a basic workflow to help you get started with Actions

name: heif2jpg

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependences & build images
        run: |
          echo Install dependeces
          sudo apt install libheif-examples
          echo Run script
          ls
          chmod +x ./script.sh
          ./script.sh ./input/*
